### ISSUE TITLE
ISO 19146 potential Geolexica redirect

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/www.isotc211.org#10]
From Mats:

> ISO 19145 has the link: http://www.isotc211.org/TermCrossMap1.htm
> Would that as 19104 also be a Geolexica redirect candidate?

ping @ReesePlews

**Comment by ronaldtse** [comment]
Sorry @ReesePlews for the very late reply, I totally missed this. I actually can't find it either. Maybe it's from another standard? @MatsAhlin ?

**Comment by ronaldtse** [comment]
Ah -- it's from 19146!
<img width="928" alt="Screen Shot 2019-03-19 at 3 18 05 PM" src="https://user-images.githubusercontent.com/11865/54587159-33ea0e80-4a5a-11e9-9fc7-2985c199508e.png">

**Comment by ReesePlews** [comment]
there is class in 19146 called TermCrossMap. but i am guessing because it was an example, that it was never realized. to me it points to a more generalized page about a possibly register. since the MLGT is considered the register if this pointed to a general information page about the online MLGT then that may be sufficient. however 19146 is Cross-domain vocabularies and this example may be more related to a register of cross-domain entries. the MLGT is not such a register.

**Comment by ronaldtse** [comment]
I see. Does this mean there is no corresponding page today and we don’t need a redirect? If so we can close this.

**Comment by jetgeo** [comment]
You can close it, the link is just an example, and not a structure we want to keep (directly under isotc211.org).
